# Generated by Django 5.2 on 2025-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default_pic.jpg", upload_to="profile_pics"
            ),
        ),
    ]
