services:
  - type: web
    name: food-orders-q
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn foodsite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: food-orders-q-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false

databases:
  - name: food-orders-q-db
    databaseName: food_orders_q
    user: food_orders_q_user 