# Generated by Django 5.1.5 on 2025-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Item_name", models.CharField(max_length=200)),
                ("Item_desc", models.TextField(max_length=500)),
                ("Item_price", models.IntegerField()),
            ],
        ),
    ]
