# Generated by Django 5.1.5 on 2025-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Item_img",
            field=models.CharField(
                default="https://cdn-icons-png.flaticon.com/512/1377/1377194.png",
                max_length=1100,
            ),
        ),
    ]
